import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/feedback/Toaster";
import PlatformFrame from "@/components/layout/PlatformFrame";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased font-sans">
      <body className="min-h-full flex flex-col">
        <PlatformFrame>{children}</PlatformFrame>
        <Toaster />
      </body>
    </html>
  );
}
